docs(app): Improve load model docs page
Tresjs/tres pull request #505
Opened 2024-01-10 19:17 UTC by JaimeTorrealba

2024-01-12 15:51 UTC, alvarosabu requested changes
![Screenshot 2024-01-12 at 16 51 14](https://github.com/Tresjs/tres/assets/4699008/ceacc3e8-69f7-45a1-95cd-e76c2293dfed)

Now that the suspense is gone, the highlighted lines are incorrect in most of the doc, could you fix them please?

2024-01-12 15:51 UTC, alvarosabu commented on docs/examples/load-models.md
> +
🙏🏻 @JaimeTorrealba

2024-01-14 14:57 UTC, JaimeTorrealba commented on docs/examples/load-models.md
> +
Done

2024-01-16 16:53 UTC, alvarosabu approved these changes

2024-01-26 13:44 UTC, JaimeTorrealba commented
@alvarosabu this is also ready, please let me know

2024-01-26 14:18 UTC, merged