Feat(app): light-shadows and shaders docs examples
Tresjs/tres pull request #506
Opened 2024-01-11 11:16 UTC by JaimeTorrealba

closes #476

2024-01-12 15:47 UTC, alvarosabu requested changes

2024-01-12 15:47 UTC, alvarosabu commented on docs/examples/shaders.md
> +
You might want to wrap this on code ` somehow, is not rendering as you are expecting 

![Screenshot 2024-01-12 at 16 41 49](https://github.com/Tresjs/tres/assets/4699008/bbab2422-5fa0-42a4-ac11-37cd08c1fe75)

2024-01-12 15:47 UTC, alvarosabu commented on docs/examples/shaders.md
> +```
```suggestion
```vue
<TresMesh :position="[0, 4, 0]">
  <TresSphereGeometry :args="[2, 32, 32]" />
  <TresShaderMaterial />
</TresMesh>
```
```

2024-01-12 15:47 UTC, alvarosabu commented on docs/examples/shaders.md
> +_Basic knowledge of how shaders work is necessary_
```suggestion
::: warning
_Basic knowledge of how shaders work is necessary
:::
```

2024-01-12 15:47 UTC, alvarosabu commented on docs/.vitepress/config.ts
> +          { text: 'Lights Shadows', link: '/examples/lights-shadows' },
```suggestion
          { text: 'Lights & Shadows', link: '/examples/lights-shadows' },
```

2024-01-12 15:47 UTC, alvarosabu commented on docs/.vitepress/config.ts
> +          { text: 'Using Shaders', link: '/examples/shaders' },
```suggestion
          { text: 'Shaders', link: '/examples/shaders' },
```

2024-01-16 16:53 UTC, alvarosabu approved these changes

2024-01-16 18:30 UTC, alvarosabu commented on docs/examples/lights-shadows.md
> +**Number 3**: Set the objects to cast or receive shadows
```suggestion
###  Set the objects to cast or receive shadows
```

2024-01-26 13:43 UTC, JaimeTorrealba commented
@alvarosabu thanks for pay attention to these details, I believe we're ready, let me know

2024-01-26 14:17 UTC, alvarosabu requested changes
@JaimeTorrealba way better now, I just added some quick suggestions for the wording of the Shadows setup, we were using the same terms everywhere, was redundant to read.

2024-01-26 14:17 UTC, alvarosabu commented on docs/examples/lights-shadows.md
> +We could divide this into three steps.
```suggestion
We could divide this into three steps:
```

2024-01-26 14:17 UTC, alvarosabu commented on docs/examples/lights-shadows.md
> +### Set the shadows on the renderer
```suggestion
### Activate shadows on the renderer
```

2024-01-26 14:17 UTC, alvarosabu commented on docs/examples/lights-shadows.md
> +## Setting our lights and shadow
```suggestion
## Enabling shadows
```

2024-01-26 14:17 UTC, alvarosabu commented on docs/examples/lights-shadows.md
> +### Set the light to cast shadow
```suggestion
### Set the light to cast shadows
```

2024-01-27 12:06 UTC, merged