initial commit: copy and change `es` folder
Tresjs/tres pull request #548
Opened 2024-02-09 12:15 UTC by DennisSmuda

Working on german translations as per [this issue](https://github.com/Tresjs/tres/issues/540).

2024-02-09 13:41 UTC, andretchen0 commented
Hey there @DennisSmuda ,

I see that you opened and closed a few PRs for the German translation. Let me know if I can lend a hand.

2024-02-09 14:14 UTC, andretchen0 commented
> > Hey there @DennisSmuda ,
> > I see that you opened and closed a few PRs for the German translation. Let me know if I can lend a hand.
> 
> yea first one was a fork, then I had to rename 🙈 this is the correct branch that I'll keep working on though. I think I can handle it, thank you 👍

No problem. It happens. 

Thanks for your contribution to the project. 😀

2024-02-11 20:04 UTC, andretchen0 commented
@DennisSmuda Thanks for this!

@alvarosabu How do you want to work the docs translation reviews? 

* Do we need another native speaker to look at the language? 
* Or do we just want to make sure that there isn't any obvious weirdness in the docs site? (In which case, I could do this review.)

2024-02-12 06:07 UTC, offskip-dave commented
@DennisSmuda @andretchen0 
I left some comments on this PR, there might be a few more spots to improve, but for now please check it. 🙏

2024-02-12 11:54 UTC, DennisSmuda commented on docs/de/advanced/caveats.md
> +Hier ist ein Benchmark, der den Unterschied zwischen der Verwendung eines Proxy-Objekts und eines einfachen Objekts zeigt.
@Tinoooo what do you think? To me "Der Benchmark" is how I've used it all my life so I'm super biased 😆

2024-02-12 12:23 UTC, Tinoooo submitted a review, later dismissed
I have only checked a portion of the files yet.

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/caveats.md
> +Hot Module Replacement (HMR) ist eine Funktion, die es dir erlaubt, deinen Code zu aktualisieren, ohne die Seite neu zu laden. Dies ist eine großartige Funktion, die die Entwicklung viel schneller ma
```suggestion
Hot Module Replacement (HMR) ist eine Funktion, die es dir erlaubt, deinen Code zu aktualisieren, ohne die Seite neu zu laden. Dies ist eine großartige Funktion, die die Entwicklung viel schneller macht. **TresJS** verwendet [Vite](https://vitejs.dev/). Es ist jedoch wirklich kompliziert, dies korrekt mit Three.js zu bewerkstelligen.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/caveats.md
> +Obwohl ein minimaler Löschfluss implementiert wurde, ist er nicht perfekt. Das bedeutet, dass du manchmal die Seite neu laden musst, um die Änderungen korrekt zu sehen, insbesondere wenn du Instanzen
```suggestion
Obwohl ein minimaler Aufräummechanismus implementiert wurde, ist er nicht perfekt. Das bedeutet, dass du manchmal die Seite neu laden musst, um die Änderungen korrekt zu sehen, insbesondere wenn du Instanzen über [Template Refs](https://v3.vuejs.org/guide/component-template-refs.html) referenzierst.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/caveats.md
> +Wenn du eine Änderung an der `color`-Eigenschaft des `TresMeshStandardMaterial`-Komponenten vornimmst, wirst du sehen, dass die Änderung angewendet wird, aber die Rotation funktioniert nicht mehr. Di
```suggestion
Wenn du eine Änderung an der `color`-Eigenschaft bei Instanzen der  `TresMeshStandardMaterial`-Komponente vornimmst, wirst du sehen, dass die Änderung angewendet wird, aber die Rotation  nicht mehr funktioniert. Dies liegt daran, dass die Instanz entfernt und neu erstellt wird.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/caveats.md
> +Also, als **Faustregel**, solltest du die Seite neu laden, wenn du die von dir vorgenommenen Änderungen nicht siehst.
```suggestion
Als **Faustregel**, solltest du die Seite neu laden, wenn du die von dir vorgenommenen Änderungen nicht siehst.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/caveats.md
> +Wir alle lieben Reaktivität 💚. Es ist eines der mächtigsten Features von VueJS. Allerdings sollten wir vorsichtig sein, wenn wir ThreeJS verwenden.
```suggestion
Wir alle lieben Reaktivität 💚. Es ist eines der mächtigsten Features von Vue.js. Allerdings sollten wir vorsichtig sein, wenn wir Three.js verwenden.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/caveats.md
> +Die Reaktivität von Vue basiert auf [Proxy](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Proxy). Dies ermöglicht es Vue 3, automatisch Änderungen an Datenobjekten zu
```suggestion
Die Reaktivität von Vue basiert auf [Proxies](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Proxy). Dies ermöglicht es Vue 3, automatisch Änderungen an Datenobjekten zu verfolgen und die entsprechenden DOM-Elemente jedes Mal zu aktualisieren, wenn sich die Daten ändern.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/caveats.md
> +Hier ist ein Benchmark, der den Unterschied zwischen der Verwendung eines Proxy-Objekts und eines einfachen Objekts zeigt.
I'd go for "der Benchmark" and "ein Benchmark".

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/caveats.md
> +Im Gegensatz zu `ref()` wird der innere Wert eines shallow ref gespeichert und so wie er ist exponiert, und es findet keine tiefe Reaktivität statt. Nur der Zugriff auf `.value` ist reaktiv. Quelle:
```suggestion
Im Gegensatz zu `ref()` wird der innere Wert eines shallow Ref gespeichert und so wie er ist exponiert. Nur der Zugriff auf `.value` ist reaktiv. Quelle: [Vue.js Docs](https://vuejs.org/api/reactivity-advanced.html#shallowref)
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/extending.md
> +Tres bietet grundlegende Funktionalitäten, aber es ist einfach, Drittanbieter-Elemente hinzuzufügen und sie in seinem internen Katalog zu erweitern.
```suggestion
Tres bietet grundlegende Funktionalitäten, aber es ist einfach, Drittanbieterelemente hinzuzufügen.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/extending.md
> +Die meisten 3D-Erlebnisse nutzen `OrbitControls`, die nicht Teil der Hauptbibliothek sind. Du kannst sie zu deinem Projekt hinzufügen, indem du sie aus dem Modul `three/addons/controls/OrbitControls`
```suggestion
Die meisten 3D-Szenen nutzen `OrbitControls`, das nicht Teil der Hauptbibliothek ist. Du kannst es zu deinem Projekt hinzufügen, indem du es aus dem Modul `three/addons/controls/OrbitControls` importierst.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/primitive.md
> +Die `<primitive />`-Komponente ist eine vielseitige Low-Level-Komponente in TresJS, die es dir ermöglicht, ohne Abstraktion jedes Objekt von three.js direkt in deiner Vue-Anwendung zu verwenden. Sie
```suggestion
Die `<primitive />`-Komponente ist eine vielseitige Low-Level-Komponente in TresJS, die es dir ermöglicht, ohne Abstraktion jedes Objekt von Three.js direkt in deiner Vue-Anwendung zu verwenden. Sie dient als Brücke zwischen dem Reaktivitätssystem von Vue und dem Szenengraph von Three.js.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/advanced/primitive.md
> +  // Crea una geometría de caja y un material básico
```suggestion
// Geometrie und Material erstellen
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/composables.md
> +Das Composable `useRenderLoop` ist der Kern der Animationen in **TresJS**. Es ermöglicht dir, einen Callback zu registrieren, der mit der nativen Aktualisierungsfrequenz aufgerufen wird. Dies ist das
```suggestion
Das Composable `useRenderLoop` ist der Kern der Animationen in **TresJS**. Es ermöglicht dir, einen Callback zu registrieren, der mit der nativen Bildwiederholrate aufgerufen wird. Dies ist das wichtigste Composable in **TresJS**.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/events.md
> +**TresJS**-Komponenten lösen Mouse-Events aus, wenn mit ihnen interagiert wird. Dies gilt für Komponenten, die Klassen von three.js repräsentieren, die von [THREE.Object3D](https://threejs.org/docs/i
```suggestion
**TresJS**-Komponenten lösen Mouse-Events aus, wenn mit ihnen interagiert wird. Dies gilt für Komponenten, die Klassen von Three.js repräsentieren, die von [THREE.Object3D](https://threejs.org/docs/index.html?q=object#api/en/core/Object3D) abgeleitet sind (wie Meshes, Groups, ...).
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/instances-arguments-and-props.md
> +Die Hauptidee von **Tres** ist ein _selbstgenerierter Katalog_ aller ThreeJS-Elemente. Dieser Katalog wird aus dem Quellcode von ThreeJS generiert, sodass er immer auf dem neuesten Stand ist.
```suggestion
Die Hauptidee von **Tres** ist ein _selbstgenerierter Katalog_ aller Three.js-Elemente. Dieser Katalog wird aus dem Quellcode von Three.js generiert, sodass er immer auf dem neuesten Stand ist.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/instances-arguments-and-props.md
> +Wenn du ThreeJS verwendest, musst du die Elemente, die du nutzen möchtest, importieren. Zum Beispiel, wenn du eine `PerspectiveCamera` verwenden möchtest, musst du sie aus dem `three` Paket importier
```suggestion
Wenn du Three.js verwendest, musst du die Elemente, die du nutzen möchtest, importieren. Zum Beispiel, wenn du eine `PerspectiveCamera` verwenden möchtest, musst du sie aus dem `three` Paket importieren:
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/instances-arguments-and-props.md
> +Einige ThreeJS-Objekte haben Argumente, zum Beispiel hat der Konstruktor `PerspectiveCamera` folgende Argumente:
```suggestion
Einige Three.js-Objekte haben Argumente. Zum Beispiel hat der Konstruktor `PerspectiveCamera` folgende Argumente:
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/instances-arguments-and-props.md
> +- `far` - Ferner Plan des Kamera-Frustums.
```suggestion
- `aspect` - Seitenverhältnis des Frustums der Kamera.
- `near` - Naher Plan des Frustums der Kamera.
- `far` - Ferner Plan des Frustums der Kamera.
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/instances-arguments-and-props.md
> +Du kannst auch Eigenschaften an die Komponente übergeben, zum Beispiel hat das `TresAmbientLight` eine Eigenschaft `intensity`, so dass du sie der Komponente folgendermaßen übergeben kannst:
```suggestion
Du kannst auch Eigenschaften an die Komponente übergeben. Zum Beispiel hat das `TresAmbientLight` eine Eigenschaft `intensity`, so dass du sie der Komponente folgendermaßen übergeben kannst:
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/instances-arguments-and-props.md
> +Alle Eigenschaften, deren zugrunde liegendes Objekt eine `.set()`-Methode hat, haben eine Kurzform, um den Wert als Array zu erhalten. Zum Beispiel hat die `TresPerspectiveCamera` eine Eigenschaft `p
```suggestion
Alle Eigenschaften, die in der zugrundeliegenden Klasse eine `.set()`-Methode haben, können via Prop als Array übergeben werden. Zum Beispiel hat die `TresPerspectiveCamera` eine Eigenschaft `position`, die ein `Vector3`-Objekt ist. Du kannst ihren Wert so setzen:
```

2024-02-12 12:23 UTC, Tinoooo commented on docs/de/api/tres-canvas.md
> +Die `TresCanvas` Komponente ist die Haupt-Komponente von Tres, welche den `WebGLRenderer` erstellt.
```suggestion
Die `TresCanvas` Komponente ist die Hauptkomponente von Tres, welche den `WebGLRenderer` erstellt.
```

2024-02-12 20:43 UTC, DennisSmuda commented
@offskip-dave I hope I got everything, thanks again 🤟

2024-02-21 22:23 UTC, Tinoooo requested changes

2024-02-21 22:23 UTC, Tinoooo commented on docs/de/directives/v-always-look-at.md
> +// Die Position der Sphäre wird verändert, aber die Kamera bleibt am Ball ⚽️
```suggestion
// Die Position der Kugel wird verändert, aber die Kamera folgt ihr.
```

2024-02-21 22:23 UTC, Tinoooo commented on docs/de/directives/v-distance-to.md
> +Mit der neuen Direktive `v-distance-to` ist es einfacher als je zuvor. Du musst nur das Zielobjekt für die Messung angeben, und das Ergebnis wird in deiner Konsole erscheinen.
```suggestion
Mit der neuen Direktive `v-distance-to` ist es einfacher als je zuvor. Du musst nur das Zielobjekt für die Messung angeben und das Ergebnis wird in deiner Konsole erscheinen.
```

2024-02-21 22:23 UTC, Tinoooo commented on docs/de/examples/basic-animations.md
> +Um den Würfel zu animieren, benötigen wir eine Referenz zu ihm. Dies können wir tun, indem wir eine [Template-Referenz](https://vuejs.org/guide/essentials/template-refs.html) verwenden, indem wir die
```suggestion
Um den Würfel zu animieren, benötigen wir eine Referenz zu ihm. Dies können wir tun, indem wir eine [Template-Referenz](https://vuejs.org/guide/essentials/template-refs.html) verwenden. Dazu verwenden wir die `ref`-Eigenschaft an der `TresMesh`-Komponente. Dies wird uns die Instanz von THREE bereitstellen.
```

2024-02-21 22:23 UTC, Tinoooo commented on docs/de/examples/basic-animations.md
> +Um die Performance zu verbessern, werden wir eine [Oberflächliche Referenz](https://v3.vuejs.org/guide/reactivity-fundamentals.html#shallow-reactivity) verwenden, um die Referenz zu speichern, anstat
```suggestion
Um die Performance zu verbessern, werden wir ein [Shallow Ref](https://v3.vuejs.org/guide/reactivity-fundamentals.html#shallow-reactivity) verwenden, um die Referenz zu speichern, anstatt einer regulären Referenz. Warum das so ist, kannst du [hier](../advanced/caveats.md#reactivity) sehen.
```

2024-02-21 22:23 UTC, Tinoooo commented on docs/de/examples/basic-animations.md
> +Du kannst auch das `delta` der [internen Uhr von THREE](https://threejs.org/docs/?q=clock#api/en/core/Clock) oder das `elapsed` nutzen, um den Würfel zu animieren.
```suggestion
Du kannst auch das `delta` der [internen Uhr von THREE](https://threejs.org/docs/?q=clock#api/en/core/Clock) oder `elapsed` nutzen, um den Würfel zu animieren.
```

2024-02-21 22:23 UTC, Tinoooo commented on docs/de/examples/lights-shadows.md
> +Wie du weißt, ist jede Instanz in [ThreeJs](https://threejs.org/) in **TresJs** verfügbar, also sind alle Arten von Lichtern ebenfalls verfügbar, wir müssen nur das Präfix `Tres` hinzufügen, um sie z
```suggestion
Wie du weißt, ist jede Instanz in [three.js](https://threejs.org/) in **TresJS** verfügbar. Also sind alle Arten von Lichtern ebenfalls verfügbar. Wir müssen nur das Präfix `Tres` hinzufügen, um sie zu nutzen.
```

2024-02-21 22:23 UTC, Tinoooo commented on docs/de/examples/lights-shadows.md
> +Aber nicht alle Lichter können Schatten erzeugen, diese Definition kommt direkt von ThreeJs und macht Sinn. Zum Beispiel ist der Zweck eines [ambientLight](https://threejs.org/docs/index.html?q=ambie
sounds weird and should be rephrased

2024-02-27 12:31 UTC, Tinoooo requested changes

2024-02-27 12:31 UTC, Tinoooo commented on docs/de/api/composables.md
> +Die Composition API von Vue 3 [Composition API](https://vuejs.org/guide/extras/composition-api-faq.html#what-is-composition-api) ermöglicht es dir, Logik und Hooks zu schreiben, die zwischen Komponen
```suggestion
Die Composition API von Vue 3 [Composition API](https://vuejs.org/guide/extras/composition-api-faq.html#what-is-composition-api) ermöglicht es dir, Logik und Hooks zu schreiben, die zwischen Komponenten wiederverwendet werden kann.
```

2024-02-27 12:31 UTC, Tinoooo commented on docs/de/api/composables.md
> +**TresJS** nutzt diese API, um eine Reihe von zusammensetzbaren Funktionen zu erstellen, die verwendet werden können, zum Beispiel um Animationen zu erstellen oder mit der Szene zu interagieren. Es e
```suggestion
**TresJS** nutzt diese API, um eine Reihe von zusammensetzbaren Funktionen zu erstellen, die verwendet werden können um zum Beispiel Animationen zu erstellen oder mit der Szene zu interagieren. Es ermöglicht dir auch, komplexere Szenen zu erstellen, die mit ausschließlich Vue-Komponenten (Texturen, Loader usw.) eventuell nicht möglich wären.
```

2024-02-27 12:31 UTC, Tinoooo commented on docs/de/api/events.md
> +**TresJS**-Komponenten lösen Mouse-Events aus, wenn mit ihnen interagiert wird. Dies gilt für Komponenten, die von [THREE.Object3D](https://threejs.org/docs/index.html?q=object#api/en/core/Object3D)
```suggestion
**TresJS**-Komponenten lösen Pointer-Events aus, wenn mit ihnen interagiert wird. Dies gilt für Komponenten, die von [THREE.Object3D](https://threejs.org/docs/index.html?q=object#api/en/core/Object3D) abgeleitet sind (wie Meshes, Groups, ...).
```

2024-02-27 12:31 UTC, Tinoooo commented on docs/de/debug/devtools.md
> +Eine der größten Herausforderungen, denen sich ein Entwickler beim Erstellen von 3D-Erlebnissen im Browser gegenübersieht, ist das Debugging. Das `<canvas>`-Element des Browsers ist eine Blackbox, un
```suggestion
Eine der größten Herausforderungen, denen sich ein Entwickler beim Erstellen von 3D-Erlebnissen im Browser gegenübersieht, ist das Debugging. Das `<canvas>`-Element des Browsers ist eine Blackbox, und es ist schwierig zu wissen, was darin passiert. Die imperative Natur von [Three.js](https://threejs.org/) macht es schwierig zu debuggen. Um zu sehen, was passiert, muss man sich auf `console.log` oder auf Drittanbieter-Tools verlassen. Auch das Messen der Performance von Szenen gestaltet sich als äußerst schwer.
```

2024-02-27 13:01 UTC, Tinoooo commented on docs/de/examples/shaders.md
> +Für unseren Blob könnten wir eine einfache `SphereGeometry` verwenden, indem wir einige `widthSegments` und `heightSegments` hinzufügen, um einen sanften Effekt zu erzielen, und unseren Blob 4 Einhei
```suggestion
Für unseren Blob können wir eine einfache `SphereGeometry` verwenden. Durch das Hinzufügen von `widthSegments` und `heightSegments` erzielen wir einen sanften Effekt. Wir platzieren unseren Blob 4 Einheiten entlang der positiven Y-Achse.
```

2024-02-27 13:03 UTC, Tinoooo commented on docs/de/examples/text-3d.md
> +[TextGeometry](https://threejs.org/docs/index.html?q=text#examples/en/geometries/TextGeometry) benötigt nur ein Argument, die Schriftart. Unten siehst du ein Beispiel.
```suggestion
[TextGeometry](https://threejs.org/docs/index.html?q=text#examples/en/geometries/TextGeometry) benötigt nur die Schriftart als Argument. Unten siehst du ein Beispiel.
```

2024-02-27 13:04 UTC, Tinoooo commented on docs/de/examples/text-3d.md
> +Es funktioniert einfach. 💯 (wenn kein Text bereitgestellt wird, wird der Text TresJS sein)
```suggestion
Es funktioniert einfach. 💯 (wenn kein Text angegeben wird, wird der Text "TresJS" sein)
```

2024-02-27 13:05 UTC, Tinoooo commented on docs/de/examples/text-3d.md
> +Standardmäßig beginnt der Text in Three.js an der Ausgangsposition des Meshs, also wenn es [0,0,0] ist, wird der Text dort beginnen, aber wir können ihn einfach zentrieren, indem wir das Flag "center
```suggestion
Der Text in Three.js beginnt standardmäßig an der Ausgangsposition des Meshs, also bei [0,0,0]. Um den Text zu zentrieren, können wir einfach das Flag "center" übergeben.
```

2024-02-27 13:06 UTC, Tinoooo commented on docs/de/guide/getting-started.md
> +Du kannst TresJS wie jedes andere Vue-Plugin installieren
```suggestion
Du kannst TresJS wie jedes andere Vue-Plugin installieren.
```

2024-02-27 13:06 UTC, Tinoooo commented on docs/de/guide/getting-started.md
> +Oder du kannst es direkt in deiner Komponente verwenden
```suggestion
Oder du kannst es direkt in deiner Komponente verwenden.
```

2024-02-27 13:06 UTC, Tinoooo commented on docs/de/guide/getting-started.md
> +Aufgrund von Performance und Größe des Bundles ist dieser Ansatz zu empfelhen, da das Tree-Shaking besser funktionieren wird und nur die tatsächlich verwendeten Komponenten importiert werden.
```suggestion
Aufgrund von Performance und Größe des Bundles ist dieser Ansatz zu empfehlen, da das Tree-Shaking besser funktionieren wird und nur die tatsächlich verwendeten Komponenten importiert werden.
```

2024-02-27 13:09 UTC, Tinoooo commented on docs/de/guide/index.md
> +Das React-Ökosystem hat eine beeindruckende Lösung für das **benutzerdefinierte Rendering** namens [react-three-fiber](https://docs.pmnd.rs/react-three-fiber), die es dir ermöglicht, deine Szenen dek
```suggestion
Das React-Ökosystem hat eine beeindruckende Lösung für das **benutzerdefinierte Rendering** namens [react-three-fiber](https://docs.pmnd.rs/react-three-fiber), die es dir ermöglicht, deine Szenen deklarativ mit wiederverwendbaren, reaktiven Komponenten zu bauen.
```

2024-02-27 13:11 UTC, Tinoooo commented on docs/de/guide/nuxt.md
> +Das ist alles! Jetzt kannst du `@tresjs/nuxt` in deiner Nuxt-Anwendung verwenden ✨
```suggestion
Das ist alles! Jetzt kannst du `@tresjs/nuxt` in deiner Nuxt-Anwendung verwenden ✨.
```

2024-02-27 13:42 UTC, Tinoooo commented on docs/de/guide/troubleshooting.md
> +Dieser Leitfaden soll dir helfen, die häufigsten Probleme zu lösen, die du beim Einsatz von TresJS v2 treffen könntest.
```suggestion
Dieser Leitfaden soll dir helfen, die häufigsten Probleme zu lösen, auf die du beim Einsatz von TresJS v2 treffen könntest.
```

2024-02-27 13:43 UTC, Tinoooo commented on docs/de/guide/troubleshooting.md
> +Du hast der [Startanleitung](/de/guide/getting-started.md) gefolgt, kannst aber deine gerenderte Szene immer noch nicht sehen.
```suggestion
Du bist der [Startanleitung](/de/guide/getting-started.md) gefolgt, kannst aber deine gerenderte Szene immer noch nicht sehen?
```

2024-02-27 13:44 UTC, Tinoooo commented on docs/de/guide/troubleshooting.md
> +Oder du kannst auch die Eigenschaft `window-size` der Komponente `TresCanvas` setzen:
```suggestion
Du kannst auch die Eigenschaft `window-size` der Komponente `TresCanvas` verwenden:
```

2024-02-27 13:45 UTC, Tinoooo commented on docs/de/guide/troubleshooting.md
> +Wir wissen, dass selbst die besten Schlafkatzen gelegentlich Fehler machen, und wir brauchen deine Hilfe, um TresJS noch besser zu machen! Wenn du einen Fehler findest, öffne bitte ein Ticket im [Rep
```suggestion
Wir wissen, dass selbst die besten Schlafkatzen gelegentlich Fehler machen und wir brauchen deine Hilfe, um TresJS noch besser zu machen! Wenn du einen Fehler findest, öffne bitte ein Ticket im [Repository](https://github.com/Tresjs/tres/issues) und **bitte stelle einen Reproduktionslink bereit**.
```

2024-02-27 13:48 UTC, Tinoooo commented on docs/de/guide/your-first-scene.md
> +Beachte, dass wir nichts importieren müssen, da **TresJS** automatisch eine **Vue-Komponente basierend auf dem Three-Objekt, das du verwenden möchtest, im CamelCase mit einem Tres-Prefix** generiert.
```suggestion
Beachte, dass wir nichts importieren müssen, da **TresJS** automatisch eine **Vue-Komponente basierend auf dem Three-Objekt, das du verwenden möchtest, im PascalCase mit einem Tres-Prefix** generiert. Wenn du zum Beispiel ein `AmbientLight` verwenden möchtest, würdest du die `TresAmbientLight`-Komponente nutzen.
```

2024-03-03 16:34 UTC, Tinoooo approved these changes

2024-03-03 16:35 UTC, merged

2024-03-04 08:06 UTC, alvarosabu commented
Hey @DennisSmuda  @Tinoooo, it seems like the PR was merged with errors, that's why it is not deployed on Netlify 

![Screenshot 2024-03-04 at 09 01 57](https://github.com/Tresjs/tres/assets/4699008/dc8132b3-3e67-474f-9153-630d86f52b4b)

![Screenshot 2024-03-04 at 09 05 34](https://github.com/Tresjs/tres/assets/4699008/4b2ccd94-5b47-41d2-b6a3-ba18c9f32985)

Could you please submit another PR with the fix for the broken link? Thanks