docs: 557 cookbook
Tresjs/tres pull request #558
Opened 2024-02-21 19:27 UTC by alvarosabu

2024-02-26 15:08 UTC, JaimeTorrealba requested changes
I love it just a couple of suggestions

The separator should be below or the title go on top, seems like the group belong to the aku aku
![image](https://github.com/Tresjs/tres/assets/63722373/c22c5e94-a55a-401f-9214-5a0f0a7f83af)

2. The images should be clickable, please. jejeje

 3. This is a question I don't see the changes of cookbook for examples in the old blog entries, is this necessary?
 
 4. Lastly another a suggestion, maybe put a little info block tell users that the spicy is difficulty :D
 
 I love the concept and the work, any others ideas for this section in the future?

2024-03-04 11:32 UTC, damienmontastier commented
Hey @alvarosabu, looking at the deploy version and the Cookbook examples, it looks like there's a problem with the Cientos version, which is causing problems with the orbit control drag smooth, which isn't working. I've seen the same problem on the Lab repo.

2024-03-04 14:45 UTC, alvarosabu commented
@Tinoooo @DennisSmuda could you please check the german translations for the cookbook?

2024-03-04 16:51 UTC, DennisSmuda commented
> @Tinoooo @DennisSmuda could you please check the german translations for the cookbook?

I did some updates - very nice work ✅

2024-03-05 08:26 UTC, merged